# starship.toml

add_newline = false

format = """
$character\
$os$hostname\
$directory\
$cmd_duration
[â””â”€>](bold green) """

right_format = """$all"""

continuation_prompt = 'â–¶â–¶ '

[character]
success_symbol = "[ï€Œ](bold green)" 
error_symbol = "[ï€](bold red)"

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow) '
disabled = false
ssh_symbol = "î¬ "

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 8
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = ' ï€£ '
format = '[$path]($style)[$read_only]($read_only_style) '

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
format = 'ó±‘ $time'

[git_branch]
symbol = "ï˜ "
format = 'via [$symbol$branch]($style)'
truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold green'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï†‡ '
modified = 'ï„ '
staged = '[++\($count\)](green)'
renamed = 'ï¡ '
deleted = 'ï€” '
